<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPCb3LC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPCb3LC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHPCb3LC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHPCb3LC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHPCb3LC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HPCb3LC',
    'container.build_id' => 'ec6b9fdb',
    'container.build_time' => 1569835041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPCb3LC');
